name:                lambada
version:             0.1.0.0
github:              "rudsvar/lambada"
license:             GPL-3
author:              "Rudi B. Svartveit"
maintainer:          "rudsvar <at> gmail <dot> com"
copyright:           "2018 Rudi B. Svartveit"

extra-source-files:
- README.md

description:         For more information check out <https://rudsvar.github.io/lambada>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: src
  dependencies:
  - containers

executables:
  lambada-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -Wall
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambada
    - haskeline
    - directory

tests:
  lambada-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - lambada
    - hspec
